[WIP] automation
Romkin7/geniobot.io pull request #9
Opened 2021-07-21 14:27 UTC by jualiasha

2021-07-21 15:38 UTC, Romkin7 requested changes

2021-07-21 15:38 UTC, Romkin7 commented on dashboard/public/automation.json
> +			"id": 1
add here categories list as array. in all automation items. we can build response from backend like this json and send it

2021-07-22 03:39 UTC, Romkin7 requested changes

2021-07-22 03:39 UTC, Romkin7 commented on dashboard/src/Pages/Automation/Automation.tsx
> +	const allcategories = automation?.map((automation: any) => automation.category);
we can't have array name in singular form it should be auomations.map((automation)=> {})

so array name is automations in plural form.

2021-07-22 10:44 UTC, jualiasha commented on dashboard/public/automation.json
> +			"id": 1
done

2021-07-22 10:44 UTC, jualiasha commented on dashboard/src/Pages/Automation/Automation.tsx
> +	const allcategories = automation?.map((automation: any) => automation.category);
done

2021-07-22 18:27 UTC, Romkin7 requested changes

2021-07-22 18:27 UTC, Romkin7 commented on dashboard/src/Pages/Automation/Automation.tsx
> +import { Route, Switch, useLocation, useParams } from 'react-router-dom';
Remove Route, Switch, useLocation, useParams from here. we obly sahould have Switch in Main.tsx and everywhere else only Link components from react-router-dom

2021-07-22 18:27 UTC, Romkin7 commented on dashboard/src/Pages/Automation/Automation.tsx
> +import { Route, Switch, useLocation, useParams } from 'react-router-dom';
But use here for this conditional rendering, routes are not needed here.

2021-07-22 20:49 UTC, Romkin7 requested changes

2021-07-22 20:49 UTC, Romkin7 commented on dashboard/src/Pages/Automation/Automation.tsx
> +		const filteredcategorylist: any = automations?.filter((automation) => {
/** Filter returns whole object based on condition, while map can return only some parts of object like only categories of automation object and leave out all the rest.
	 * We can also chain map and filter, like i do here, i do map on filtered array of automation objects and return only categories.
	 */

2021-07-23 07:15 UTC, Romkin7 approved these changes

2021-07-23 07:17 UTC, Romkin7 requested changes

2021-07-23 07:17 UTC, Romkin7 commented on dashboard/src/Pages/Automation/Automation.tsx
> +								active={
active should be boolean prop not class. active true or false. based on that boolean value add class active or not active.

2021-07-24 05:23 UTC, Romkin7 requested changes

2021-07-24 05:23 UTC, Romkin7 commented on dashboard/src/Components/Topic/Topic.tsx
> +const Topics: FC<any> = ({ topic }) => {
Please don't use any in for props types, try avoid any type unless you can't do anything else and can't move on without it.

2021-07-24 05:23 UTC, Romkin7 commented on dashboard/src/Components/Topic/Topic.tsx
> +const Topics: FC<any> = ({ topic }) => {
no any types for props, create interfaces instead as i did for Category.tsx
```
interface ICategoryProps {
	category: string;
	categoryClickHandler: (category: string) => void;
	active: boolean | null;
}

const Category: FC<ICategoryProps> = ({ category, categoryClickHandler, active }) => {
	return (
```

2021-07-24 05:23 UTC, Romkin7 commented on dashboard/src/Components/Topic/Topic.tsx
> +import { Link, Route, Switch, useParams } from 'react-router-dom';
remove Route and Switch from here, we don't use Route or Switch outside of Main.tsx Switch and more Switch than that one.

2021-07-25 10:36 UTC, Romkin7 approved these changes

2021-07-25 10:36 UTC, merged